//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsBooks.ServiceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceService.IBookstoreService")]
    public interface IBookstoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/DoWork", ReplyAction="http://tempuri.org/IBookstoreService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/DoWork", ReplyAction="http://tempuri.org/IBookstoreService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
        System.Collections.Generic.List<object> GetBooks(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<object>> GetBooksAsync(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetAllBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetAllBooksResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
        System.Collections.Generic.List<object> GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetAllBooks", ReplyAction="http://tempuri.org/IBookstoreService/GetAllBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<object>> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetGeneralNewsFeed", ReplyAction="http://tempuri.org/IBookstoreService/GetGeneralNewsFeedResponse")]
        System.Collections.Generic.List<string> GetGeneralNewsFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookstoreService/GetGeneralNewsFeed", ReplyAction="http://tempuri.org/IBookstoreService/GetGeneralNewsFeedResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetGeneralNewsFeedAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookstoreServiceChannel : WindowsFormsBooks.ServiceService.IBookstoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookstoreServiceClient : System.ServiceModel.ClientBase<WindowsFormsBooks.ServiceService.IBookstoreService>, WindowsFormsBooks.ServiceService.IBookstoreService {
        
        public BookstoreServiceClient() {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookstoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public System.Collections.Generic.List<object> GetBooks(string searchString) {
            return base.Channel.GetBooks(searchString);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<object>> GetBooksAsync(string searchString) {
            return base.Channel.GetBooksAsync(searchString);
        }
        
        public System.Collections.Generic.List<object> GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<object>> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public System.Collections.Generic.List<string> GetGeneralNewsFeed() {
            return base.Channel.GetGeneralNewsFeed();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetGeneralNewsFeedAsync() {
            return base.Channel.GetGeneralNewsFeedAsync();
        }
    }
}
