//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSMS_Big.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPT_RESURS
    {
        public string SIGN { get; set; }
        public string NAMN { get; set; }
        public string ADRESS { get; set; }
        public string POSTNR { get; set; }
        public string POSTADR { get; set; }
        public string TELNR { get; set; }
        public string FODD { get; set; }
        public string FNR { get; set; }
        public string TYP { get; set; }
        public string AKTIV { get; set; }
        public decimal RESURSTYPID { get; set; }
        public decimal TIDINTERVALL { get; set; }
        public Nullable<System.DateTime> SCHEMA_FOM { get; set; }
        public Nullable<System.DateTime> SCHEMA_TOM { get; set; }
        public Nullable<decimal> SCHEMA_CYKELTID { get; set; }
        public Nullable<decimal> SCHEMA_CYKLISK { get; set; }
        public Nullable<decimal> SCHEMA_ID { get; set; }
        public string KLINKOD { get; set; }
        public Nullable<decimal> TIDBOKBAR { get; set; }
        public string LOSENORD { get; set; }
        public string VETID { get; set; }
        public string TITEL { get; set; }
        public Nullable<decimal> RIGHTS_TO_SIGN { get; set; }
        public Nullable<decimal> SIGN_RECEPT { get; set; }
        public Nullable<decimal> SIGN_DIAGNOS { get; set; }
        public Nullable<decimal> SENASTE_DEPONI { get; set; }
        public Nullable<decimal> PWD_CHECK_SIGNERA { get; set; }
        public Nullable<decimal> PWD_CHECK_BETMOT { get; set; }
        public Nullable<decimal> SENASTE_KVITTONR { get; set; }
        public Nullable<decimal> SENASTE_KRE_KVITTO { get; set; }
        public Nullable<decimal> SENASTE_KONT_BET { get; set; }
        public Nullable<decimal> PWD_CHECK_DAGANT { get; set; }
        public Nullable<decimal> PWD_CHECK_ORDINERA { get; set; }
        public string FORSKRIVARKOD { get; set; }
        public Nullable<decimal> PWD_CHECK_ERECEPT { get; set; }
    }
}
