//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSMS_Big.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPT_TIDBOK
    {
        public System.DateTime DATUM { get; set; }
        public string SIGN { get; set; }
        public string TID { get; set; }
        public decimal MINUTER { get; set; }
        public string JOURNALNR { get; set; }
        public string ORSAK { get; set; }
        public decimal BOKNINGSTYPID { get; set; }
        public string X_KUNDNR { get; set; }
        public string X_KUNDNAMN { get; set; }
        public string X_HEMTEL { get; set; }
        public string X_ARBTEL { get; set; }
        public string X_ALTTEL { get; set; }
        public string X_DJURNAMN { get; set; }
        public string X_RAS { get; set; }
        public decimal VTFNR { get; set; }
        public decimal SCHEMA { get; set; }
        public string BOKSIGN { get; set; }
        public Nullable<decimal> SEQID { get; set; }
        public string X_PERSNR { get; set; }
        public Nullable<decimal> INTERVALL { get; set; }
        public string TJGTYPID { get; set; }
        public Nullable<decimal> AVSLUTAD { get; set; }
        public string TJGTYPID_OUT { get; set; }
        public Nullable<decimal> NATT_SCHEMA { get; set; }
    }
}
