//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSMS_Big.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPT_KLINKOD
    {
        public string KLIN { get; set; }
        public string NAMN { get; set; }
        public Nullable<decimal> DEB { get; set; }
        public string BESOKAVG { get; set; }
        public string FAKTAVG { get; set; }
        public string POSTNR { get; set; }
        public string POSTADRESS { get; set; }
        public string GATUADRESS { get; set; }
        public string TELEFON { get; set; }
        public byte[] LOGO { get; set; }
        public string RECEPT_BES { get; set; }
        public string RECEPT_TEL { get; set; }
        public string RECEPT_ARVODE_TXT { get; set; }
        public byte[] ERECEPT_CERT { get; set; }
        public string ERECEPT_PWD { get; set; }
        public Nullable<short> AGRESSO_VERNR { get; set; }
        public string AGRESSO_KOD { get; set; }
        public string AGRESSO_DEFAVD { get; set; }
        public string AGRIA_OMBUDSNR { get; set; }
        public string AGRIA_EPOST_REPLY { get; set; }
        public string AGRIA_FAX { get; set; }
        public Nullable<decimal> AGRIA_SVARTYP { get; set; }
    }
}
